export interface Quote {
  cat: string;
  sub: string;
  text: string;
  author: string;
}

export const QUOTES: Quote[] = [
  // ─── INSPIRATIONAL ───
  { cat: "Inspirational", sub: "Positive Inspirational", text: "Life is 10% what happens to you and 90% how you react to it.", author: "Charles R. Swindoll" },
  { cat: "Inspirational", sub: "Positive Inspirational", text: "Once you replace negative thoughts with positive ones, you'll start having positive results.", author: "Willie Nelson" },
  { cat: "Inspirational", sub: "Positive Inspirational", text: "The positive thinker sees the invisible, feels the intangible, and achieves the impossible.", author: "Winston Churchill" },
  { cat: "Inspirational", sub: "Positive Inspirational", text: "When you want something, all the universe conspires in helping you to achieve it.", author: "Paulo Coelho" },
  { cat: "Inspirational", sub: "Positive Inspirational", text: "What you focus on expands, and when you focus on the goodness in your life, you create more of it.", author: "Oprah Winfrey" },
  { cat: "Inspirational", sub: "Positive Inspirational", text: "Nurture your mind with great thoughts, for you will never go any higher than you think.", author: "Benjamin Disraeli" },
  { cat: "Inspirational", sub: "Positive Inspirational", text: "Turn your face to the sun and the shadows fall behind you.", author: "Maori Proverb" },
  { cat: "Inspirational", sub: "Positive Inspirational", text: "Create the highest, grandest vision possible for your life, because you become what you believe.", author: "Oprah Winfrey" },
  { cat: "Inspirational", sub: "Positive Inspirational", text: "We are all here for some special reason. Stop being a prisoner of your past. Become the architect of your future.", author: "Robin S. Sharma" },
  { cat: "Inspirational", sub: "Positive Inspirational", text: "Perpetual optimism is a force multiplier.", author: "Colin Powell" },

  { cat: "Inspirational", sub: "Inspirational for Women", text: "The success of every woman should be the inspiration to another. We should raise each other up.", author: "Serena Williams" },
  { cat: "Inspirational", sub: "Inspirational for Women", text: "Each time a woman stands up for herself, she stands up for all women.", author: "Maya Angelou" },
  { cat: "Inspirational", sub: "Inspirational for Women", text: "I had to make my own living and my own opportunity. Don't sit down and wait for the opportunities to come.", author: "Madam C.J. Walker" },
  { cat: "Inspirational", sub: "Inspirational for Women", text: "Strength doesn't come from what you can do. It comes from overcoming the things you once thought you couldn't.", author: "Rikki Rogers" },
  { cat: "Inspirational", sub: "Inspirational for Women", text: "Fight for the things that you care about, but do it in a way that will lead others to join you.", author: "Ruth Bader Ginsburg" },
  { cat: "Inspirational", sub: "Inspirational for Women", text: "Real integrity is doing the right thing, knowing that nobody's going to know whether you did it or not.", author: "Oprah Winfrey" },
  { cat: "Inspirational", sub: "Inspirational for Women", text: "When I dare to be powerful, to use my strength in the service of my vision, it becomes less important whether I am afraid.", author: "Audre Lorde" },
  { cat: "Inspirational", sub: "Inspirational for Women", text: "You can't use up creativity. The more you use, the more you have.", author: "Maya Angelou" },
  { cat: "Inspirational", sub: "Inspirational for Women", text: "I don't focus on what I'm up against. I focus on my goals and I try to ignore the rest.", author: "Venus Williams" },
  { cat: "Inspirational", sub: "Inspirational for Women", text: "Never let someone's opinion become your reality. Never sacrifice who you are.", author: "Les Brown" },

  { cat: "Inspirational", sub: "Inspirational Life", text: "The two most important days in your life are the day you are born and the day you find out why.", author: "Mark Twain" },
  { cat: "Inspirational", sub: "Inspirational Life", text: "If you love life, don't waste time, for time is what life is made up of.", author: "Bruce Lee" },
  { cat: "Inspirational", sub: "Inspirational Life", text: "You gain strength, courage and confidence by every experience in which you really stop to look fear in the face.", author: "Eleanor Roosevelt" },
  { cat: "Inspirational", sub: "Inspirational Life", text: "Courage doesn't always roar. Sometimes courage is the little voice at the end of the day that says I'll try again tomorrow.", author: "Mary Anne Radmacher" },
  { cat: "Inspirational", sub: "Inspirational Life", text: "And those who were seen dancing were thought to be insane by those who could not hear the music.", author: "Friedrich Nietzsche" },
  { cat: "Inspirational", sub: "Inspirational Life", text: "The future depends on what you do today.", author: "Mahatma Gandhi" },
  { cat: "Inspirational", sub: "Inspirational Life", text: "Finish each day and be done with it. Tomorrow is a new day. You shall begin it serenely.", author: "Ralph Waldo Emerson" },
  { cat: "Inspirational", sub: "Inspirational Life", text: "You will never change your life until you change something you do daily.", author: "Mike Murdock" },
  { cat: "Inspirational", sub: "Inspirational Life", text: "Live with intention. Walk to the edge. Listen hard. Practice wellness. Play with abandon. Laugh.", author: "Mary Anne Radmacher" },
  { cat: "Inspirational", sub: "Inspirational Life", text: "I refuse to accept the view that mankind is so tragically bound to the starless midnight of racism and war.", author: "Martin Luther King Jr." },

  { cat: "Inspirational", sub: "Short Inspirational", text: "Don't wish it were easier. Wish you were better.", author: "Jim Rohn" },
  { cat: "Inspirational", sub: "Short Inspirational", text: "If you really want to do something, you'll find a way. If you don't, you'll find an excuse.", author: "Jim Rohn" },
  { cat: "Inspirational", sub: "Short Inspirational", text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki" },
  { cat: "Inspirational", sub: "Short Inspirational", text: "A winner is a dreamer who never gives up.", author: "Nelson Mandela" },
  { cat: "Inspirational", sub: "Short Inspirational", text: "If you are always trying to be normal, you will never know how amazing you can be.", author: "Maya Angelou" },
  { cat: "Inspirational", sub: "Short Inspirational", text: "The way to get started is to quit talking and start doing.", author: "Walt Disney" },
  { cat: "Inspirational", sub: "Short Inspirational", text: "Fall in love with the process, and the results will come.", author: "Eric Thomas" },
  { cat: "Inspirational", sub: "Short Inspirational", text: "There are two types of pain: the pain of discipline and the pain of regret.", author: "Jim Rohn" },
  { cat: "Inspirational", sub: "Short Inspirational", text: "Don't limit yourself. Many people limit themselves to what they think they can do.", author: "Mary Kay Ash" },
  { cat: "Inspirational", sub: "Short Inspirational", text: "If you don't ask, the answer is always no.", author: "Nora Roberts" },

  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "Chase the vision, not the money. The money will end up following you.", author: "Tony Hsieh" },
  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "If you are not willing to risk the unusual, you will have to settle for the ordinary.", author: "Jim Rohn" },
  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "When 99% of people doubt your idea, you're either gravely wrong or about to make history.", author: "Scott Belsky" },
  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "Throw me to the wolves and I will return leading the pack.", author: "Unknown" },
  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "The activity you're most avoiding contains your biggest opportunity.", author: "Robin S. Sharma" },
  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "You may never know what results come of your actions, but if you do nothing, there will be no results.", author: "Mahatma Gandhi" },
  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "Strength does not come from winning. Your struggles develop your strengths.", author: "Arnold Schwarzenegger" },
  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "Hard work beats talent when talent doesn't work hard.", author: "Tim Notke" },
  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "Don't make excuses for why you can't get it done. Focus on all the reasons why you must make it happen.", author: "Les Brown" },
  { cat: "Inspirational", sub: "Inspirational Entrepreneurship", text: "Your time is limited, so don't waste it living someone else's life.", author: "Steve Jobs" },

  { cat: "Inspirational", sub: "Inspirational Business", text: "If people like you they'll listen to you, but if they trust you they'll do business with you.", author: "Zig Ziglar" },
  { cat: "Inspirational", sub: "Inspirational Business", text: "People will forget what you said, but people will never forget how you made them feel.", author: "Maya Angelou" },
  { cat: "Inspirational", sub: "Inspirational Business", text: "Success is no accident. It is hard work, perseverance, learning, studying, sacrifice and love of what you are doing.", author: "Pele" },
  { cat: "Inspirational", sub: "Inspirational Business", text: "You don't build a business. You build people, and then people build the business.", author: "Zig Ziglar" },
  { cat: "Inspirational", sub: "Inspirational Business", text: "Outstanding leaders go out of their way to boost the self-esteem of their personnel.", author: "Sam Walton" },
  { cat: "Inspirational", sub: "Inspirational Business", text: "Successful people do what unsuccessful people are not willing to do.", author: "Jim Rohn" },
  { cat: "Inspirational", sub: "Inspirational Business", text: "Leadership is not about titles, positions or flowcharts. It is about one life influencing another.", author: "John C. Maxwell" },
  { cat: "Inspirational", sub: "Inspirational Business", text: "My father taught me to always do more than you get paid for as an investment in your future.", author: "Jim Rohn" },
  { cat: "Inspirational", sub: "Inspirational Business", text: "The key to success is to focus our conscious mind on things we desire not things we fear.", author: "Brian Tracy" },
  { cat: "Inspirational", sub: "Inspirational Business", text: "When you do more than you're paid to do, eventually you'll be paid more for what you do.", author: "Zig Ziglar" },

  { cat: "Inspirational", sub: "Inspirational for Men", text: "The true test of a man's character is what he does when no one is watching.", author: "John Wooden" },
  { cat: "Inspirational", sub: "Inspirational for Men", text: "Work hard at your job and you can make a living. Work hard on yourself and you can make a fortune.", author: "Jim Rohn" },
  { cat: "Inspirational", sub: "Inspirational for Men", text: "Weak men wait for opportunities; strong men make them.", author: "Orison Swett Marden" },
  { cat: "Inspirational", sub: "Inspirational for Men", text: "He is a man of courage who does not run away, but remains at his post and fights against the enemy.", author: "Socrates" },
  { cat: "Inspirational", sub: "Inspirational for Men", text: "So don't be average. Don't be good. Don't be great. Be phenomenal. Or be forgotten.", author: "Eric Thomas" },
  { cat: "Inspirational", sub: "Inspirational for Men", text: "Make up your mind that no matter what comes your way, you will do more than simply survive. You will thrive.", author: "Joel Osteen" },
  { cat: "Inspirational", sub: "Inspirational for Men", text: "I am not the richest, smartest or most talented person in the world, but I succeed because I keep going.", author: "Sylvester Stallone" },
  { cat: "Inspirational", sub: "Inspirational for Men", text: "The most difficult thing is the decision to act. The rest is merely tenacity.", author: "Amelia Earhart" },
  { cat: "Inspirational", sub: "Inspirational for Men", text: "Nothing in life is to be feared, it is only to be understood.", author: "Marie Curie" },
  { cat: "Inspirational", sub: "Inspirational for Men", text: "Survival can be summed up in three words: never give up.", author: "Bear Grylls" },

  { cat: "Inspirational", sub: "Christian Inspirational", text: "Your life as a Christian should make non-believers question their disbelief in God.", author: "Dietrich Bonhoeffer" },
  { cat: "Inspirational", sub: "Christian Inspirational", text: "God is too good to be unkind, too wise to be mistaken; and when you cannot trace His hand, you can trust His heart.", author: "Charles H. Spurgeon" },
  { cat: "Inspirational", sub: "Christian Inspirational", text: "When you keep God in first place, He will take you to places you've never dreamed of.", author: "Joel Osteen" },
  { cat: "Inspirational", sub: "Christian Inspirational", text: "In the midst of your battles, never forget that God loves you and He has a plan for you.", author: "Unknown" },
  { cat: "Inspirational", sub: "Christian Inspirational", text: "God would not have put a dream in your heart if He had not already given you everything you need to fulfill it.", author: "Joel Osteen" },
  { cat: "Inspirational", sub: "Christian Inspirational", text: "Through hard work, perseverance and a faith in God, you can live your dreams.", author: "Ben Carson" },
  { cat: "Inspirational", sub: "Christian Inspirational", text: "Let no one ever come to you without leaving better and happier.", author: "Mother Teresa" },
  { cat: "Inspirational", sub: "Christian Inspirational", text: "Never worry about numbers. Help one person at a time and always start with the person nearest you.", author: "Mother Teresa" },
  { cat: "Inspirational", sub: "Christian Inspirational", text: "Trust God for the impossible. Miracles are His department. Our job is to do our best.", author: "Unknown" },
  { cat: "Inspirational", sub: "Christian Inspirational", text: "You were made by God and for God, and until you understand that, life will never make sense.", author: "Rick Warren" },

  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "Joy does not simply happen to us. We have to choose joy and keep choosing it every day.", author: "Henri J.M. Nouwen" },
  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "Don't let your alarm clock be the only reason you wake up.", author: "Unknown" },
  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "When you are living the best version of yourself, you inspire others to live the best versions of themselves.", author: "Steve Maraboli" },
  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "Be here. Be present. Wherever you are, be there.", author: "Willie Nelson" },
  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "A positive attitude will have positive results because attitudes are contagious.", author: "Joyce Meyer" },
  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "Stay curious, keep learning and keep growing. Always strive to be more interested than interesting.", author: "Robin S. Sharma" },
  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "All your life, you will be faced with a choice. You can choose love or hate. I choose love.", author: "Johnny Cash" },
  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "Go to bed early and wake up early. The morning hours are good.", author: "Jeff Bezos" },
  { cat: "Inspirational", sub: "Good Morning Inspirational", text: "Happiness is a state of mind. It's just according to the way you look at things.", author: "Walt Disney" },

  { cat: "Inspirational", sub: "Blessed Quotes", text: "Every day is a gift from God. There's no guarantee of tomorrow, so make the most of it.", author: "Joel Osteen" },
  { cat: "Inspirational", sub: "Blessed Quotes", text: "Let no one ever come to you without leaving better and happier. Be the living expression of God's kindness.", author: "Mother Teresa" },
  { cat: "Inspirational", sub: "Blessed Quotes", text: "Don't you quit. You keep walking, you keep trying. There is help and happiness ahead.", author: "Jeffrey R. Holland" },
  { cat: "Inspirational", sub: "Blessed Quotes", text: "Better than a thousand hollow words is one word that brings peace.", author: "Buddha" },
  { cat: "Inspirational", sub: "Blessed Quotes", text: "Act like you're blessed. Talk like you're blessed. Walk like you're blessed.", author: "Joel Osteen" },
  { cat: "Inspirational", sub: "Blessed Quotes", text: "When you focus on being a blessing, God makes sure that you are always blessed in abundance.", author: "Joel Osteen" },
  { cat: "Inspirational", sub: "Blessed Quotes", text: "Never be in a hurry; do everything quietly and in a calm spirit. Do not lose your inner peace for anything.", author: "Saint Francis de Sales" },
  { cat: "Inspirational", sub: "Blessed Quotes", text: "Love cannot remain by itself. Love has to be put into action, and that action is service.", author: "Mother Teresa" },
  { cat: "Inspirational", sub: "Blessed Quotes", text: "Body is purified by water. Ego by tears. Intellect is purified by knowledge. And soul is purified with love.", author: "Ali ibn Abi Talib" },
  { cat: "Inspirational", sub: "Blessed Quotes", text: "Trust the process of your life unfolding, and know with certainty that your soul rests safe in the arms of God.", author: "Neale Donald Walsch" },

  // ─── MOTIVATIONAL ───
  { cat: "Motivational", sub: "Motivational for Success", text: "I've missed more than 9000 shots in my career. I've failed over and over again. And that is why I succeed.", author: "Michael Jordan" },
  { cat: "Motivational", sub: "Motivational for Success", text: "You are the master of your destiny. You can influence, direct and control your own environment.", author: "Napoleon Hill" },
  { cat: "Motivational", sub: "Motivational for Success", text: "The only limit to the height of your achievements is the reach of your dreams and your willingness to work hard.", author: "Michelle Obama" },
  { cat: "Motivational", sub: "Motivational for Success", text: "Success is nothing more than a few simple disciplines, practiced every day.", author: "Jim Rohn" },
  { cat: "Motivational", sub: "Motivational for Success", text: "You were born to win, but to be a winner you must plan to win, prepare to win, and expect to win.", author: "Zig Ziglar" },
  { cat: "Motivational", sub: "Motivational for Success", text: "Success is never on discount. Greatness is never on sale. It's all or nothing. It's all day, every day.", author: "Eric Thomas" },
  { cat: "Motivational", sub: "Motivational for Success", text: "A dream written down with a date becomes a goal. A goal broken down into steps becomes a plan.", author: "Greg Reid" },
  { cat: "Motivational", sub: "Motivational for Success", text: "There are no limits on what you can achieve with your life, except the limits you accept in your mind.", author: "Brian Tracy" },
  { cat: "Motivational", sub: "Motivational for Success", text: "Remember that all success is based on long-term commitment, faith, discipline and attitude.", author: "Jim Rohn" },
  { cat: "Motivational", sub: "Motivational for Success", text: "Goals. There's no telling what you can do when you get inspired by them and act upon them.", author: "Jim Rohn" },

  { cat: "Motivational", sub: "Motivational for Work", text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki" },
  { cat: "Motivational", sub: "Motivational for Work", text: "What ever you do, do it well. Do it so well that when people see you do it they will want to come back.", author: "Walt Disney" },
  { cat: "Motivational", sub: "Motivational for Work", text: "You don't get paid for the hour. You get paid for the value you bring to the hour.", author: "Jim Rohn" },
  { cat: "Motivational", sub: "Motivational for Work", text: "Starve your distractions, feed your focus.", author: "Unknown" },
  { cat: "Motivational", sub: "Motivational for Work", text: "Move fast. A sense of urgency is the one thing you can develop that will separate you from everyone else.", author: "Brian Tracy" },
  { cat: "Motivational", sub: "Motivational for Work", text: "Investing in yourself is the best thing you can do. If you've got talents, no one can take them from you.", author: "Warren Buffett" },
  { cat: "Motivational", sub: "Motivational for Work", text: "It has been my observation that most people get ahead during the time that others waste.", author: "Henry Ford" },
  { cat: "Motivational", sub: "Motivational for Work", text: "In the world of business, the people who are most successful are those who are doing what they love.", author: "Warren Buffett" },
  { cat: "Motivational", sub: "Motivational for Work", text: "People work better when they know what the goal is and why.", author: "Elon Musk" },
  { cat: "Motivational", sub: "Motivational for Work", text: "Daily ripples of excellence over time become a tsunami of success.", author: "Robin S. Sharma" },

  { cat: "Motivational", sub: "Motivational About Life", text: "God, grant me the serenity to accept the things I cannot change, courage to change the things I can.", author: "Reinhold Niebuhr" },
  { cat: "Motivational", sub: "Motivational About Life", text: "The greatest discovery of all time is that a person can change his future by merely changing his attitude.", author: "Oprah Winfrey" },
  { cat: "Motivational", sub: "Motivational About Life", text: "Go confidently in the direction of your dreams. Live the life you've imagined.", author: "Henry David Thoreau" },
  { cat: "Motivational", sub: "Motivational About Life", text: "Tell me, what is it you plan to do with your one wild and precious life?", author: "Mary Oliver" },
  { cat: "Motivational", sub: "Motivational About Life", text: "If you have infinite patience and perseverance, success is bound to come.", author: "Swami Vivekananda" },
  { cat: "Motivational", sub: "Motivational About Life", text: "The curious paradox is that when I accept myself just as I am, then I can change.", author: "Carl Rogers" },
  { cat: "Motivational", sub: "Motivational About Life", text: "We reap what we sow. We are the makers of our own fate.", author: "Swami Vivekananda" },
  { cat: "Motivational", sub: "Motivational About Life", text: "You can be anything you want to be, if only you believe with sufficient conviction.", author: "Napoleon Hill" },
  { cat: "Motivational", sub: "Motivational About Life", text: "You can't avoid pain, but you can choose to overcome it.", author: "Unknown" },
  { cat: "Motivational", sub: "Motivational About Life", text: "You will never change your life until you change something you do daily.", author: "Mike Murdock" },

  { cat: "Motivational", sub: "Powerful Motivational", text: "It is not the critic who counts. The credit belongs to the man who is actually in the arena.", author: "Theodore Roosevelt" },
  { cat: "Motivational", sub: "Powerful Motivational", text: "You will never ever be successful until you turn your pain into greatness.", author: "Eric Thomas" },
  { cat: "Motivational", sub: "Powerful Motivational", text: "My attitude is that if you push me towards something that you think is a weakness, I will turn that into a strength.", author: "Michael Jordan" },
  { cat: "Motivational", sub: "Powerful Motivational", text: "If your dreams do not scare you, they are not big enough.", author: "Ellen Johnson Sirleaf" },
  { cat: "Motivational", sub: "Powerful Motivational", text: "The mind always fails first, not the body. The secret is to make your mind work for you, not against you.", author: "Arnold Schwarzenegger" },
  { cat: "Motivational", sub: "Powerful Motivational", text: "There's no talent here, this is hard work. This is an obsession. Talent does not exist, we are all equal as human beings.", author: "Conor McGregor" },
  { cat: "Motivational", sub: "Powerful Motivational", text: "The resistance that you fight physically in the gym and in life can only build a strong character.", author: "Arnold Schwarzenegger" },
  { cat: "Motivational", sub: "Powerful Motivational", text: "You are not your circumstances. You are your possibilities. If you know that, you can do anything.", author: "Oprah Winfrey" },
  { cat: "Motivational", sub: "Powerful Motivational", text: "Push yourself to do more and to experience more. Harness your energy to start expanding your dreams.", author: "Robin S. Sharma" },
  { cat: "Motivational", sub: "Powerful Motivational", text: "I am willing. I am wired to win. I embrace the uncertainty. I am relentless.", author: "Inky Johnson" },

  { cat: "Motivational", sub: "Short Motivational", text: "The way to get started is to quit talking and start doing.", author: "Walt Disney" },
  { cat: "Motivational", sub: "Short Motivational", text: "If you don't ask, the answer is always no.", author: "Nora Roberts" },
  { cat: "Motivational", sub: "Short Motivational", text: "Fall in love with the process, and the results will come.", author: "Eric Thomas" },
  { cat: "Motivational", sub: "Short Motivational", text: "Real leadership is being the person others will gladly and confidently follow.", author: "John C. Maxwell" },
  { cat: "Motivational", sub: "Short Motivational", text: "You can always do more than you think you can.", author: "Unknown" },
  { cat: "Motivational", sub: "Short Motivational", text: "Have goals so big your problems pale in comparison.", author: "Grant Cardone" },
  { cat: "Motivational", sub: "Short Motivational", text: "When you stop learning you stop growing.", author: "Unknown" },
  { cat: "Motivational", sub: "Short Motivational", text: "Don't think about what can happen in a month. Just focus on the 24 hours in front of you.", author: "Eric Thomas" },
  { cat: "Motivational", sub: "Short Motivational", text: "The key to SUCCESS is to START before you're ready.", author: "Marie Forleo" },
  { cat: "Motivational", sub: "Short Motivational", text: "Be obsessed with improvement.", author: "Unknown" },

  { cat: "Motivational", sub: "Positive Motivational", text: "Positive thinking can be contagious. Being surrounded by winners helps you develop into a winner.", author: "Arnold Schwarzenegger" },
  { cat: "Motivational", sub: "Positive Motivational", text: "There is little difference in people, but that little difference makes a big difference. The little difference is attitude.", author: "W. Clement Stone" },
  { cat: "Motivational", sub: "Positive Motivational", text: "Every single second is an opportunity to change your life, because in any moment you can change the way you feel.", author: "Rhonda Byrne" },
  { cat: "Motivational", sub: "Positive Motivational", text: "No one can create negativity or stress within you. Only you can do that by virtue of how you process your world.", author: "Wayne W. Dyer" },
  { cat: "Motivational", sub: "Positive Motivational", text: "You cannot always control what goes on outside. But you can always control what goes on inside.", author: "Wayne W. Dyer" },
  { cat: "Motivational", sub: "Positive Motivational", text: "I may not have gone where I intended to go, but I think I have ended up where I needed to be.", author: "Douglas Adams" },
  { cat: "Motivational", sub: "Positive Motivational", text: "I will love the light for it shows me the way, yet I will endure the darkness because it shows me the stars.", author: "Og Mandino" },
  { cat: "Motivational", sub: "Positive Motivational", text: "Set your mind on a definite goal and observe how quickly the world stands aside to let you pass.", author: "Napoleon Hill" },
  { cat: "Motivational", sub: "Positive Motivational", text: "Perpetual optimism is a force multiplier.", author: "Colin Powell" },
  { cat: "Motivational", sub: "Positive Motivational", text: "With everything that has happened to you, you can treat what has happened as a gift.", author: "Wayne W. Dyer" },

  { cat: "Motivational", sub: "Motivational for Women", text: "Women and girls can do whatever they want. There is no limit to what we as women can accomplish.", author: "Michelle Obama" },
  { cat: "Motivational", sub: "Motivational for Women", text: "I believe in pink. I believe that laughing is the best calorie burner. I believe in being strong when everything seems to be going wrong.", author: "Audrey Hepburn" },
  { cat: "Motivational", sub: "Motivational for Women", text: "You either walk inside your story and own it or you stand outside your story and hustle for your worthiness.", author: "Brene Brown" },
  { cat: "Motivational", sub: "Motivational for Women", text: "The most difficult thing is the decision to act, the rest is merely tenacity.", author: "Amelia Earhart" },
  { cat: "Motivational", sub: "Motivational for Women", text: "Speak up. Believe in yourself. Take risks.", author: "Sheryl Sandberg" },
  { cat: "Motivational", sub: "Motivational for Women", text: "Step out of the history that is holding you back. Step into the new story you are willing to create.", author: "Oprah Winfrey" },
  { cat: "Motivational", sub: "Motivational for Women", text: "Beauty is being the best possible version of yourself, inside and out.", author: "Audrey Hepburn" },
  { cat: "Motivational", sub: "Motivational for Women", text: "Fight for the things that you care about, but do it in a way that will lead others to join you.", author: "Ruth Bader Ginsburg" },
  { cat: "Motivational", sub: "Motivational for Women", text: "I had to make my own living and my own opportunity. Don't sit down and wait for the opportunities to come.", author: "Madam C.J. Walker" },
  { cat: "Motivational", sub: "Motivational for Women", text: "Never let someone's opinion become your reality.", author: "Les Brown" },

  { cat: "Motivational", sub: "Monday Morning", text: "You master Monday! You start winning the day! You start winning the week! Then the month! Then the year!", author: "Eric Thomas" },
  { cat: "Motivational", sub: "Monday Morning", text: "This morning did you wake up to an alarm clock or an opportunity clock?", author: "Zig Ziglar" },
  { cat: "Motivational", sub: "Monday Morning", text: "I believe if you keep your faith, you keep your trust, you keep the right attitude, you'll see God open up new doors.", author: "Joel Osteen" },
  { cat: "Motivational", sub: "Monday Morning", text: "Stay curious, keep learning and keep growing. Always strive to be more interested than interesting.", author: "Robin S. Sharma" },
  { cat: "Motivational", sub: "Monday Morning", text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki" },
  { cat: "Motivational", sub: "Monday Morning", text: "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.", author: "William James" },
  { cat: "Motivational", sub: "Monday Morning", text: "Don't let your alarm clock be the only reason you wake up.", author: "Unknown" },
  { cat: "Motivational", sub: "Monday Morning", text: "The start of something new brings the hope of something great.", author: "Unknown" },
  { cat: "Motivational", sub: "Monday Morning", text: "Make today so awesome, yesterday gets jealous.", author: "Unknown" },
  { cat: "Motivational", sub: "Monday Morning", text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },

  { cat: "Motivational", sub: "Motivational Monday", text: "Success is neither magical nor mysterious. Success is the natural consequence of consistently applying basic fundamentals.", author: "Jim Rohn" },
  { cat: "Motivational", sub: "Motivational Monday", text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
  { cat: "Motivational", sub: "Motivational Monday", text: "Patience, persistence and perspiration make an unbeatable combination for success.", author: "Napoleon Hill" },
  { cat: "Motivational", sub: "Motivational Monday", text: "When you are tough on yourself, life is going to be infinitely easier on you.", author: "Zig Ziglar" },
  { cat: "Motivational", sub: "Motivational Monday", text: "The ability to discipline yourself to delay gratification is the indispensable prerequisite for success.", author: "Brian Tracy" },
  { cat: "Motivational", sub: "Motivational Monday", text: "Develop success from failures. Discouragement and failure are two of the surest stepping stones to success.", author: "Dale Carnegie" },
  { cat: "Motivational", sub: "Motivational Monday", text: "We must all suffer one of two things: the pain of discipline or the pain of regret.", author: "Jim Rohn" },
  { cat: "Motivational", sub: "Motivational Monday", text: "If I fail, I try again, and again, and again.", author: "Nick Vujicic" },
  { cat: "Motivational", sub: "Motivational Monday", text: "The key of success is for you to set one big, challenging goal and then pay any price to achieve it.", author: "Brian Tracy" },
  { cat: "Motivational", sub: "Motivational Monday", text: "Two roads diverged in a wood and I took the one less traveled by, and that has made all the difference.", author: "Robert Frost" },

  { cat: "Motivational", sub: "Friday Motivational", text: "Always wake up with a smile knowing that today you are going to accomplish what others are too afraid to do.", author: "Mark Cuban" },
  { cat: "Motivational", sub: "Friday Motivational", text: "Anyone can give up; it is the easiest thing in the world to do. But to hold it together when everyone expects you to fall apart, that is true strength.", author: "Unknown" },
  { cat: "Motivational", sub: "Friday Motivational", text: "It's not the load that breaks you down, it's the way you carry it.", author: "Lou Holtz" },
  { cat: "Motivational", sub: "Friday Motivational", text: "I've found that luck is quite predictable. If you want more luck, take more chances.", author: "Brian Tracy" },
  { cat: "Motivational", sub: "Friday Motivational", text: "As I walked out the door toward freedom, I knew if I didn't leave my bitterness and hatred behind, I'd still be in prison.", author: "Nelson Mandela" },
  { cat: "Motivational", sub: "Friday Motivational", text: "Dare to be free, dare to go as far as your thought leads, and dare to carry that out in your life.", author: "Swami Vivekananda" },
  { cat: "Motivational", sub: "Friday Motivational", text: "If you want to have more, you have to become more!", author: "Jim Rohn" },
  { cat: "Motivational", sub: "Friday Motivational", text: "The youth of today are the leaders of tomorrow.", author: "Nelson Mandela" },
  { cat: "Motivational", sub: "Friday Motivational", text: "Two roads diverged in a wood and I took the one less traveled by, and that has made all the difference.", author: "Robert Frost" },
  { cat: "Motivational", sub: "Friday Motivational", text: "Every single second is an opportunity to change your life.", author: "Rhonda Byrne" },

  { cat: "Motivational", sub: "Wednesday Motivational", text: "Vulnerability is the birthplace of innovation, creativity and change.", author: "Brene Brown" },
  { cat: "Motivational", sub: "Wednesday Motivational", text: "The key to success is to focus our conscious mind on things we desire not things we fear.", author: "Brian Tracy" },
  { cat: "Motivational", sub: "Wednesday Motivational", text: "Destiny is no matter of chance. It is a matter of choice. It is not a thing to be waited for.", author: "William Jennings Bryan" },
  { cat: "Motivational", sub: "Wednesday Motivational", text: "If you're walking down the right path and you're willing to keep walking, eventually you'll make progress.", author: "Barack Obama" },
  { cat: "Motivational", sub: "Wednesday Motivational", text: "There is nothing more powerful than a changed mind.", author: "T.D. Jakes" },
  { cat: "Motivational", sub: "Wednesday Motivational", text: "Most people fail, not because of lack of desire, but because of lack of commitment.", author: "Vince Lombardi" },
  { cat: "Motivational", sub: "Wednesday Motivational", text: "Every time you are tempted to react in the same old way, ask if you want to be a prisoner of the past or a pioneer of the future.", author: "Deepak Chopra" },
  { cat: "Motivational", sub: "Wednesday Motivational", text: "Practice the philosophy of continuous improvement. Get a little bit better every single day.", author: "Brian Tracy" },
  { cat: "Motivational", sub: "Wednesday Motivational", text: "When you cease to dream you cease to live.", author: "Malcolm Forbes" },
  { cat: "Motivational", sub: "Wednesday Motivational", text: "You don't build a business. You build people, and then people build the business.", author: "Zig Ziglar" },

  { cat: "Motivational", sub: "Motivational Workout", text: "The secret is contained in a three-part formula: self confidence, a positive mental attitude, and honest hard work.", author: "Arnold Schwarzenegger" },
  { cat: "Motivational", sub: "Motivational Workout", text: "Failure gave me strength. Pain was my motivation.", author: "Michael Jordan" },
  { cat: "Motivational", sub: "Motivational Workout", text: "It's not about the number of hours you practice, it's about the number of hours your mind is present.", author: "Kobe Bryant" },
  { cat: "Motivational", sub: "Motivational Workout", text: "The most difficult part of the training is training your mind. You build calluses on your mind to endure the pain.", author: "David Goggins" },
  { cat: "Motivational", sub: "Motivational Workout", text: "The vision of a champion is bent over, drenched in sweat, at the point of exhaustion, when nobody else is looking.", author: "Mia Hamm" },
  { cat: "Motivational", sub: "Motivational Workout", text: "In 10 sessions you'll feel the difference, in 20 you'll see the difference, and in 30 you'll have a new body.", author: "Joseph Pilates" },
  { cat: "Motivational", sub: "Motivational Workout", text: "There's no talent here, this is hard work. This is an obsession. Talent does not exist, we are all equal.", author: "Conor McGregor" },
  { cat: "Motivational", sub: "Motivational Workout", text: "The resistance that you fight physically in the gym and in life can only build a strong character.", author: "Arnold Schwarzenegger" },
  { cat: "Motivational", sub: "Motivational Workout", text: "You are stopping you. You are giving up instead of getting hard.", author: "David Goggins" },
  { cat: "Motivational", sub: "Motivational Workout", text: "The mind always fails first, not the body. The secret is to make your mind work for you.", author: "Arnold Schwarzenegger" },

  { cat: "Motivational", sub: "Good Morning Motivational", text: "Every morning you have two choices: continue to sleep with your dreams or wake up and chase them.", author: "Unknown" },
  { cat: "Motivational", sub: "Good Morning Motivational", text: "Rise up, start fresh, see the bright opportunity in each new day.", author: "Unknown" },
  { cat: "Motivational", sub: "Good Morning Motivational", text: "You've got to get up every morning with determination if you're going to go to bed with satisfaction.", author: "George Lorimer" },
  { cat: "Motivational", sub: "Good Morning Motivational", text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { cat: "Motivational", sub: "Good Morning Motivational", text: "Each morning we are born again. What we do today matters most.", author: "Buddha" },
  { cat: "Motivational", sub: "Good Morning Motivational", text: "With the new day comes new strength and new thoughts.", author: "Eleanor Roosevelt" },
  { cat: "Motivational", sub: "Good Morning Motivational", text: "Your future is created by what you do today, not tomorrow.", author: "Robert Kiyosaki" },
  { cat: "Motivational", sub: "Good Morning Motivational", text: "Don't let your alarm clock be the only reason you wake up.", author: "Unknown" },
  { cat: "Motivational", sub: "Good Morning Motivational", text: "Joy does not simply happen to us. We have to choose joy and keep choosing it every day.", author: "Henri J.M. Nouwen" },
  { cat: "Motivational", sub: "Good Morning Motivational", text: "Be here. Be present. Wherever you are, be there.", author: "Willie Nelson" },

  { cat: "Motivational", sub: "Motivational Work", text: "You master Monday! You start winning the day! You start winning the week!", author: "Eric Thomas" },
  { cat: "Motivational", sub: "Motivational Work", text: "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better.", author: "Jim Rohn" },
  { cat: "Motivational", sub: "Motivational Work", text: "Daily ripples of excellence over time become a tsunami of success.", author: "Robin S. Sharma" },
  { cat: "Motivational", sub: "Motivational Work", text: "To succeed in your mission, you must have single-minded devotion to your goal.", author: "A.P.J. Abdul Kalam" },
  { cat: "Motivational", sub: "Motivational Work", text: "The ability to discipline yourself to delay gratification is the indispensable prerequisite for success.", author: "Brian Tracy" },
  { cat: "Motivational", sub: "Motivational Work", text: "Thinking should become your capital asset, no matter what ups and downs you come across.", author: "A.P.J. Abdul Kalam" },
  { cat: "Motivational", sub: "Motivational Work", text: "There is no limit to the power of the human mind. The more concentrated it is, the more power is brought to bear on one point.", author: "Swami Vivekananda" },
  { cat: "Motivational", sub: "Motivational Work", text: "Remember why you started, remember where you're headed, and keep going.", author: "Unknown" },
  { cat: "Motivational", sub: "Motivational Work", text: "Move fast. A sense of urgency is the one thing you can develop that will separate you from everyone else.", author: "Brian Tracy" },
  { cat: "Motivational", sub: "Motivational Work", text: "Push yourself to do more and to experience more. Harness your energy to start expanding your dreams.", author: "Robin S. Sharma" },
];

export const CATEGORIES = [...new Set(QUOTES.map(q => q.cat))];
export const SUBCATEGORIES = [...new Set(QUOTES.map(q => q.sub))];

export function getQuotesByCategory(cat: string) {
  return QUOTES.filter(q => q.cat === cat);
}

export function getQuotesBySubcategory(sub: string) {
  return QUOTES.filter(q => q.sub === sub);
}

export function getSubcategoriesByCategory(cat: string) {
  return [...new Set(QUOTES.filter(q => q.cat === cat).map(q => q.sub))];
}
